development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  #server: "https://biachat.herokuapp.com/faye"
  #secret_token: "2b236c2fba47f8b2e7a6df29c0246da616d8c92d304a3756b744315f03ea8350"
  server: "https://biafta.herokuapp.com/faye"
  secret_token: "1e94debc5789cc720f569fdfabb2a870ac0c19179b319a64f86569228396d132"
  signature_expiration: 3600 # one hour
